name: cloudnottapp2
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+27

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.3
  flutter_svg:
  go_router: ^14.6.0
  google_fonts: ^6.2.1
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  blur: ^4.0.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  collection: ^1.18.0

  # csc_picker: ^0.2.7
  image_picker: ^1.1.2

  # intl: ^0.20.2 # Downgrade to match appflowy_editor

  table_calendar: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.9.5
  file_picker: ^9.0.2
  record: ^5.2.0
  audioplayers: ^6.1.2
  youtube_player_flutter: ^9.1.1
  flutter_pdfview: ^1.4.0
  top_snackbar_flutter: ^3.1.0
  provider: ^6.1.2
  # flutter_webrtc: ^0.12.1+hotfix.1
  # flutter_webrtc: ^0.14.1
  socket_io_client: ^3.0.0
  flutter_background: ^1.3.0+1
  permission_handler: ^11.3.1
  dio: ^5.7.0
  graphql_flutter: ^5.1.2
  hive: ^2.2.3
  # google_sign_in: ^6.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  marquee: ^2.3.0

  date_time: ^0.12.0

  skeletonizer: ^2.0.1
  flutter_markdown: ^0.7.6+2
  multi_dropdown: ^3.0.1
  html: ^0.15.5
  markdown: ^7.3.0
  flutter_html: ^3.0.0
  share_plus: ^10.1.4
  pdf: ^3.11.3
  screenshot: ^3.0.0
  printing: ^5.14.2
  flutter_skeleton_ui: ^0.0.6
  url_launcher: ^6.3.1
  sentry_flutter: ^8.14.1
  pay_with_paystack: ^1.0.13
  easy_pdf_viewer:
    git:
      url: https://github.com/ShankarKakumani/pdf_viewer.git
      ref: main
  percent_indicator: ^4.2.5
  webview_flutter: ^4.11.0
  intl: 0.20.2
  # image_picker: ^0.8.9
  flutter_quill: ^11.4.1
  livekit_client: ^2.4.8
  # livekit_client: ^2.3.1+hotfix.1

dependency_overrides:
  intl: 0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/app/
    - assets/icons/
    - assets/dummy_file/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app/pre_cloudnottapp2.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/pre_cloudnottapp2.png"
